### ISSUE TITLE
Add YAML/fluff.yaml linter/vetter to help users

### ISSUE THREAD

**Issue by rwxrob** [rwxrob/fluff#10]

**Comment by olzemal** [comment]
Here are some ideas:

* parse the given yaml file into a defined struct
  * this way we can verify only expected fields and throw an error if any unknown fields were given.

* verifying valid values (values for ... must be ....):
  * `machines[*].name` -> a non empty string
  * `machines[*].cores` -> greater than 0*
  * `machines[*].memory` -> greater than 1024*
  * `machines[*].volumes[*].size` -> greater than 0*
  * `machines[*].url` -> a valid url (and end in an image format)
  * `machines[*].base` -> a name present in the machines array
  * `cloud[*].name` -> a non empty string
  * `cloud[*].summary` -> optional?
  * `cloud[*].instances[*].name` -> a non empty string
  * `cloud[*].instances[*].machine` -> a name present in the machines array
  * `cloud[*].instances[*].address` -> a valid IPv4 address
  * `cloud[*].instances[*].count` -> greater than 0

\* what are the minimum sizes for the vms - and on that thought would it make sense to simplify them using t-shirt sizes?

```yaml
# ----------------------------- machines -----------------------------

machines:
- name: alma8.server
  cores: 2
  memory: 2048
  volumes:
    - size: 100
  url: |
    https://repo.almalinux.org/almalinux/8/cloud/x86_64/images/AlmaLinux-8-GenericCloud-8.5-20211119.x86_64.qcow2
- name: alma8.node
  base: alma8.server
  cores: 1

# ------------------------------ clouds ------------------------------

clouds:

# default cloud
 
- name: basic
  summary: |
    Simple control and three node mini-cloud suitable for testing
    basic endpoint architecture and applications such as Kubernetes
    installed with kubeadm. Default IPs: 192.168.132.10-13.
  instances:
  - name: control              # control
    machine: alma8.server 
    address: 192.168.132.10
    count: 1
  - name: node                 # node-1, node-2, node-3
    machine: alma8.node
    address: 192.168.132.20    # .20, .21, .22
    count: 3

# end default cloud
```
